name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-public:
    runs-on: self-hosted

    steps:
      - name: deploy-public
        run: |
          http_code=$(curl -sS -o response.txt -w "%{http_code}" \
            http://caddy-public.internal.kybe.xyz:9999/hooks/redeploy)

          cat response.txt

          if [ "$http_code" = "500" ]; then
            echo "Webhook returned 500"
            exit 1
          fi
    
  deploy-internal:
    runs-on: self-hosted

    steps:
      - name: deploy-internal
        run: |
          http_code=$(curl -sS -o response.txt -w "%{http_code}" \
            http://caddy-internal.internal.kybe.xyz:9999/hooks/redeploy)

          cat response.txt

          if [ "$http_code" = "500" ]; then
            echo "Webhook returned 500"
            exit 1
          fi
